version: '3.9'

services:
  tarantool:
    image: tarantool/tarantool:2.11-ubuntu20.04
    networks:
      - tarantool-net
    ports:
      - "3301:3301/tcp"
    volumes:
      - db_data_tarantool:/var/lib/tarantool:rw

  redis:
    image: redis:7.0.11-alpine3.18
    ports:
      - "6379:6379/tcp"
    volumes:
      - db_data_redis:/data:rw
    networks:
      - tarantool-net

  app:
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - tarantool-net
    depends_on:
      - redis
      - tarantool

networks:
  tarantool-net:
    driver: bridge

volumes:
  db_data_redis:
  db_data_tarantool: