version: '3.9'

services:
  tarantool1:
    image: tarantool/tarantool:latest
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
    networks:
      - tarantool-net
    ports:
      - "3301:3301"
    volumes:
      - db_data1:/var/lib/tarantool:rw

  tarantool2:
    image: tarantool/tarantool:latest
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
    networks:
      - tarantool-net
    ports:
      - "3302:3301"
    volumes:
      - db_data2:/var/lib/tarantool:rw

networks:
  tarantool-net:
    driver: bridge

volumes:
  db_data1:
  db_data2: